### PR TITLE
CLOUD-58744 Move regarding how to update cbd / Cloudbreak into separa…

### PR DESCRIPTION
**Pull request by mhmxs**
@akanto plz review

### CODE REVIEW

**Comment by dbialek2** [comment]
@mhmxs @akanto 
 Some editorial feedback...  Can you change the content in deployer.md/setup.md/deployer.md to:

If you need to run `cbd update`, refer to [Cloudbreak Deployer Update](update.md#update-cloudbreak-deployer). Most of the `cbd` commands require `root` permissions.

**Comment by dbialek2** [comment]
@mhmxs @akanto 
Some edits for update.md:

# Update Cloudbreak Deployer

To update Cloudbreak Deployer to the newest version, run the following commands on the console where your `Profile` is located:
 
- Stop all of the running Cloudbreak components:
```
cbd kill
```
- Update Cloudbreak Deployer:
```
cbd update
```
- Update the `docker-compose.yml` file with new Docker containers that are needed for the `cbd`:
```
cbd regenerate
```
- Remove obsolete containers, if other Cloudbreak instance doesn't use old versions:
```
cbd util cleanup
```
- Check the health and version of the updated `cbd`: 
```
cbd doctor
```
- Start the new version of the `cbd`:
```
cbd start
```
> Since Cloudbreak needs to download updated docker images for the new version, this step may take a while.

**Comment by dbialek2** [comment]
@mhmxs @akanto  Do you need to run these commands as root user?

**Comment by mhmxs** [comment]
@dbialek2 Sometimes yes, sometimes not. It depends on the environment. That's why we don't force sudo on each cbd command.

**Comment by mhmxs** [comment]
@dbialek2 is it ok for you?

**Comment by dbialek2** [comment]
@mhmxs Thanks for answering. Yes, it's OK, I just suggested some edits earlier.

**Pull request merged**
