### PR TITLE
Update releasenodes.md

### PR DESCRIPTION
**Pull request by dbialek2**
Adding 1.6.2 features pointed out by Jeff in BUG-72292

@akanto @lalyos @matyix @martonsereg @keyki @aszegedi @doktoric @mhmxs 

Tried to clarify the "Fixes & Changes" section but for most part I don't know which Jiras the fixes refer to. In teh cases where I found the jiras, they were cryptic too. So - to be honest - I don't know what most of the items under Fixes & Changes mean... And I don't know if customers will... Maybe someone who knows could clarify? Or if @sposetti  is OK with that, we can leave them as they are. We wanted to have this out ASAP.

### CODE REVIEW

**Comment by dbialek2** [comment]
Added corrections based on Attila's feedback. Please incorporate the PR and update the docs.
@akanto @lalyos @matyix @martonsereg @keyki @aszegedi @doktoric @mhmxs

@sposetti

**Comment by doktoric** [comment]
@dbialek2 we also supporting existing kerberos which was added to documentation in this pull request https://github.com/sequenceiq/cloudbreak-docs/pull/158/files

**Comment by dbialek2** [comment]
@doktoric How is that different from what we list here?

| Kerberos | **Technical Preview** Support for enabling Kerberos on the HDP clusters deployed by Cloudbreak. See [Kerberos](kerberos.md) for more information. |

CC @sposetti

**Comment by sposetti** [comment]
@dbialek2 yea, it's the same but the note as is: the Kerb option remains TP, even with this new addition.

**Comment by doktoric** [comment]
@dbialek2 in the latest releases you could only deploy clusters with new kerberos service for every cluster (Ambari deployed this). The new way is you can use an existing kerberos if you already have a deployed one.

**Comment by dbialek2** [comment]
@doktoric  @sposetti said that we don't need to mention this in RNs

**Comment by doktoric** [comment]
@dbialek2 ok

**Comment by sposetti** [comment]
@doktoric  with this merge in place (thanks), can you also push the update live?

http://sequenceiq.com/cloudbreak-docs/release-1.6.2/releasenotes/

**Comment by doktoric** [comment]
@sposetti pushed. http://sequenceiq.com/cloudbreak-docs/latest/releasenotes/

**Pull request merged**
